### ISSUE TITLE
S10 - Handlebars

### ISSUE THREAD

**Issue by K-do** [gen-classroom/projet-oe#73]
##### Description :
Implémentation de la classe Handlebars et tests unitaires
##### Temps : 
estimé : 2 h
min : 1 h
max : 2h30

**Comment by K-do** [comment]
Start now 15:14

**Comment by K-do** [comment]
Fin de l'implémentation à 17:15 (durée 2h)

**Comment by K-do** [comment]
les tests suivront

**Comment by K-do** [comment]
Debut tests unitaire 09:30

**Comment by FionaGbn** [comment]
Fin tests unitairees 10:05

**Comment by FionaGbn** [comment]
Durée totale: 2h35
