### ISSUE TITLE
S17 - Code quality

### ISSUE THREAD

**Issue by Ga-3tan** [gen-classroom/projet-oe#95]
##### Description :
Choisir et configurer un outil pour détecter les bugs et vulnérabilité du code.
##### Temps : 
estimé : 1h
min : 45min
max : 1h15
réel: 55min

**Comment by K-do** [comment]
1st session : 30min

**Comment by K-do** [comment]
restarting now at 12:20

**Comment by K-do** [comment]
ended 12:30
