### ISSUE TITLE
S18 - Code benchmarking

### ISSUE THREAD

**Issue by Ga-3tan** [gen-classroom/projet-oe#96]
##### Description :
Configurer JMH pour mesurer les performances du code (compilateur markdown et/ou Handlebars). Configurer VisualVM pour profiler un exécution de build. Inclure les données dans le rapport.
##### Temps : 
pour la configuration JMH:
estimé : 1h
min : 30min
max : 1h30
réel: 50min

pour la configuration VisualVM:
estimé : 1h
min : 30min
max : 1h30
réel: 1h30

**Comment by FionaGbn** [comment]
starting now: 11h30

**Comment by FionaGbn** [comment]
stop now: 12h20

**Comment by FionaGbn** [comment]
restarting now: 13h -> visualVM

**Comment by FionaGbn** [comment]
stop now : 14h

**Comment by FionaGbn** [comment]
restarting now: 10h30

**Comment by FionaGbn** [comment]
finished now: 11h
